Add support for Sublime
dandavison/iterm2-dwim pull request #1
Opened 2017-08-17 13:29 UTC by clnoll

- Adds support for Sublime
- Adds a `settings.py` file for editor configuration

2017-08-17 13:54 UTC, dandavison requested changes
Thank you very much for this! I've made a few comments about the exact way in which we handle the selection of text editor.

2017-08-17 13:54 UTC, dandavison commented on iterm2_dwim/editors/emacs.py
> +        super(Emacs, self).__init__(path, line)
Looks like this `__init__` method can be omitted entirely, right?

2017-08-17 13:54 UTC, dandavison commented on iterm2_dwim/settings.py
> +editor = <'emacs' OR 'sublime'>
Even though the user is required to set this, how about we make it legal python code, e.g.

```python
editor = None  # Set this to 'emacs' or 'sublime'
```

2017-08-17 13:54 UTC, dandavison commented on iterm2_dwim/editors/sublime.py
> +        super(Sublime, self).__init__(path, line)
ditto

2017-08-17 13:54 UTC, dandavison commented on iterm2_dwim/__init__.py
> +Editor = sublime.Sublime if editor.lower() == 'sublime' else emacs.Emacs
If you approve of my suggestion below, here would be slightly different, something like

```python
if settings.editor.sublime_path:
    Editor = sublime.Sublime(settings.sublime_path)
elif settings.editor.emacsclient_path:
    Editor = emacs.Emacs(settings.emacsclient_path)
else:
    exc = Exception('No editor specified in settings.py')
    notify(exc)
    raise exc
```

2017-08-17 13:54 UTC, dandavison commented on iterm2_dwim/__init__.py
> +from iterm2_dwim.settings import editor
nit: I prefer importing the `settings` module, then it is clear in the code that something like `settings.emacsclient_path` is a setting.

2017-08-17 13:54 UTC, dandavison commented on iterm2_dwim/settings.py
> +path_to_subl = None
Actually, what do you think about this slightly different scheme?

```python
# To select your editor, set one of the following to the absolute path to the
# relevant executable file on your system
emacsclient_path = None
sublime_path = None  # Note: this executable is usually called 'subl'
```

2017-08-17 15:37 UTC, clnoll commented on iterm2_dwim/editors/emacs.py
> +        super(Emacs, self).__init__(path, line)
Removed.

2017-08-17 15:37 UTC, clnoll commented on iterm2_dwim/settings.py
> +editor = <'emacs' OR 'sublime'>
Edited per your comment below.

2017-08-17 15:37 UTC, clnoll commented on iterm2_dwim/settings.py
> +path_to_subl = None
I like it! Changed.

2017-08-17 15:37 UTC, clnoll commented on iterm2_dwim/editors/sublime.py
> +        super(Sublime, self).__init__(path, line)
Removed.

2017-08-17 15:37 UTC, clnoll commented on iterm2_dwim/__init__.py
> +from iterm2_dwim.settings import editor
Makes sense, fixed.

2017-08-17 15:37 UTC, clnoll commented on iterm2_dwim/__init__.py
> +Editor = sublime.Sublime if editor.lower() == 'sublime' else emacs.Emacs
I put this in `main`.

I also used your example to instantiate the Editor classes with `settings.<path to client>`, and made `path` and `line` arguments to each editor's `visit_file` method.

2017-08-18 10:34 UTC, dandavison approved these changes
This is great, thanks very much for the contribution.

2017-08-18 10:34 UTC, merged